/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_SRC_PROTOBUFF_SMAQ2OSS_PB_H_INCLUDED
#define PB_SRC_PROTOBUFF_SMAQ2OSS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _CallControl {
    int32_t call_event;
} CallControl;

typedef struct _CallNotification {
    char number[16];
    char name[32];
    int32_t command;
} CallNotification;

typedef struct _Forecast {
    int32_t condition;
    int32_t temperature_min;
    int32_t temperature_max;
} Forecast;

typedef struct _MessageNotification {
    uint32_t timestamp;
    int32_t type;
    char sender[32];
    char subject[32];
    char body[200];
} MessageNotification;

typedef struct _MusicControl {
    int32_t music_event;
} MusicControl;

typedef struct _MusicInfo {
    char artist[32];
    char album[32];
    char track[64];
} MusicInfo;

typedef struct _SetTime {
    int32_t timestamp;
} SetTime;

typedef struct _SetWeather {
    int32_t timestamp;
    int32_t condition;
    int32_t temperature;
    int32_t temperature_min;
    int32_t temperature_max;
    int32_t humidity;
    pb_size_t forecasts_count;
    Forecast forecasts[3];
} SetWeather;


/* Initializer values for message structs */
#define SetTime_init_default                     {0}
#define MusicControl_init_default                {0}
#define CallControl_init_default                 {0}
#define Forecast_init_default                    {0, 0, 0}
#define SetWeather_init_default                  {0, 0, 0, 0, 0, 0, 0, {Forecast_init_default, Forecast_init_default, Forecast_init_default}}
#define MessageNotification_init_default         {0, 0, "", "", ""}
#define CallNotification_init_default            {"", "", 0}
#define MusicInfo_init_default                   {"", "", ""}
#define SetTime_init_zero                        {0}
#define MusicControl_init_zero                   {0}
#define CallControl_init_zero                    {0}
#define Forecast_init_zero                       {0, 0, 0}
#define SetWeather_init_zero                     {0, 0, 0, 0, 0, 0, 0, {Forecast_init_zero, Forecast_init_zero, Forecast_init_zero}}
#define MessageNotification_init_zero            {0, 0, "", "", ""}
#define CallNotification_init_zero               {"", "", 0}
#define MusicInfo_init_zero                      {"", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define CallControl_call_event_tag               1
#define CallNotification_number_tag              1
#define CallNotification_name_tag                2
#define CallNotification_command_tag             3
#define Forecast_condition_tag                   1
#define Forecast_temperature_min_tag             2
#define Forecast_temperature_max_tag             3
#define MessageNotification_timestamp_tag        1
#define MessageNotification_type_tag             2
#define MessageNotification_sender_tag           3
#define MessageNotification_subject_tag          4
#define MessageNotification_body_tag             5
#define MusicControl_music_event_tag             1
#define MusicInfo_artist_tag                     1
#define MusicInfo_album_tag                      2
#define MusicInfo_track_tag                      3
#define SetTime_timestamp_tag                    1
#define SetWeather_timestamp_tag                 1
#define SetWeather_condition_tag                 2
#define SetWeather_temperature_tag               3
#define SetWeather_temperature_min_tag           4
#define SetWeather_temperature_max_tag           5
#define SetWeather_humidity_tag                  6
#define SetWeather_forecasts_tag                 7

/* Struct field encoding specification for nanopb */
#define SetTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    timestamp,         1)
#define SetTime_CALLBACK NULL
#define SetTime_DEFAULT NULL

#define MusicControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    music_event,       1)
#define MusicControl_CALLBACK NULL
#define MusicControl_DEFAULT NULL

#define CallControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    call_event,        1)
#define CallControl_CALLBACK NULL
#define CallControl_DEFAULT NULL

#define Forecast_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    condition,         1) \
X(a, STATIC,   SINGULAR, INT32,    temperature_min,   2) \
X(a, STATIC,   SINGULAR, INT32,    temperature_max,   3)
#define Forecast_CALLBACK NULL
#define Forecast_DEFAULT NULL

#define SetWeather_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    timestamp,         1) \
X(a, STATIC,   SINGULAR, INT32,    condition,         2) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       3) \
X(a, STATIC,   SINGULAR, INT32,    temperature_min,   4) \
X(a, STATIC,   SINGULAR, INT32,    temperature_max,   5) \
X(a, STATIC,   SINGULAR, INT32,    humidity,          6) \
X(a, STATIC,   REPEATED, MESSAGE,  forecasts,         7)
#define SetWeather_CALLBACK NULL
#define SetWeather_DEFAULT NULL
#define SetWeather_forecasts_MSGTYPE Forecast

#define MessageNotification_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, INT32,    type,              2) \
X(a, STATIC,   SINGULAR, STRING,   sender,            3) \
X(a, STATIC,   SINGULAR, STRING,   subject,           4) \
X(a, STATIC,   SINGULAR, STRING,   body,              5)
#define MessageNotification_CALLBACK NULL
#define MessageNotification_DEFAULT NULL

#define CallNotification_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   number,            1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, INT32,    command,           3)
#define CallNotification_CALLBACK NULL
#define CallNotification_DEFAULT NULL

#define MusicInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   artist,            1) \
X(a, STATIC,   SINGULAR, STRING,   album,             2) \
X(a, STATIC,   SINGULAR, STRING,   track,             3)
#define MusicInfo_CALLBACK NULL
#define MusicInfo_DEFAULT NULL

extern const pb_msgdesc_t SetTime_msg;
extern const pb_msgdesc_t MusicControl_msg;
extern const pb_msgdesc_t CallControl_msg;
extern const pb_msgdesc_t Forecast_msg;
extern const pb_msgdesc_t SetWeather_msg;
extern const pb_msgdesc_t MessageNotification_msg;
extern const pb_msgdesc_t CallNotification_msg;
extern const pb_msgdesc_t MusicInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetTime_fields &SetTime_msg
#define MusicControl_fields &MusicControl_msg
#define CallControl_fields &CallControl_msg
#define Forecast_fields &Forecast_msg
#define SetWeather_fields &SetWeather_msg
#define MessageNotification_fields &MessageNotification_msg
#define CallNotification_fields &CallNotification_msg
#define MusicInfo_fields &MusicInfo_msg

/* Maximum encoded size of messages (where known) */
#define SetTime_size                             11
#define MusicControl_size                        11
#define CallControl_size                         11
#define Forecast_size                            33
#define SetWeather_size                          171
#define MessageNotification_size                 285
#define CallNotification_size                    61
#define MusicInfo_size                           131

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
