# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protobuff/smaq2oss.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/protobuff/smaq2oss.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1csrc/protobuff/smaq2oss.proto\"\x1c\n\x07SetTime\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\"#\n\x0cMusicControl\x12\x13\n\x0bmusic_event\x18\x01 \x01(\x05\"!\n\x0b\x43\x61llControl\x12\x12\n\ncall_event\x18\x01 \x01(\x05\"O\n\x08\x46orecast\x12\x11\n\tcondition\x18\x01 \x01(\x05\x12\x17\n\x0ftemperature_min\x18\x02 \x01(\x05\x12\x17\n\x0ftemperature_max\x18\x03 \x01(\x05\"\xa9\x01\n\nSetWeather\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x11\n\tcondition\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x12\x17\n\x0ftemperature_min\x18\x04 \x01(\x05\x12\x17\n\x0ftemperature_max\x18\x05 \x01(\x05\x12\x10\n\x08humidity\x18\x06 \x01(\x05\x12\x1c\n\tforecasts\x18\x07 \x03(\x0b\x32\t.Forecast\"e\n\x13MessageNotification\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\"A\n\x10\x43\x61llNotification\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\x05\"9\n\tMusicInfo\x12\x0e\n\x06\x61rtist\x18\x01 \x01(\t\x12\r\n\x05\x61lbum\x18\x02 \x01(\t\x12\r\n\x05track\x18\x03 \x01(\tb\x06proto3'
)




_SETTIME = _descriptor.Descriptor(
  name='SetTime',
  full_name='SetTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SetTime.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)


_MUSICCONTROL = _descriptor.Descriptor(
  name='MusicControl',
  full_name='MusicControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='music_event', full_name='MusicControl.music_event', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=97,
)


_CALLCONTROL = _descriptor.Descriptor(
  name='CallControl',
  full_name='CallControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_event', full_name='CallControl.call_event', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=132,
)


_FORECAST = _descriptor.Descriptor(
  name='Forecast',
  full_name='Forecast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='condition', full_name='Forecast.condition', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature_min', full_name='Forecast.temperature_min', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature_max', full_name='Forecast.temperature_max', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=213,
)


_SETWEATHER = _descriptor.Descriptor(
  name='SetWeather',
  full_name='SetWeather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SetWeather.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition', full_name='SetWeather.condition', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='SetWeather.temperature', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature_min', full_name='SetWeather.temperature_min', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature_max', full_name='SetWeather.temperature_max', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='SetWeather.humidity', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forecasts', full_name='SetWeather.forecasts', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=385,
)


_MESSAGENOTIFICATION = _descriptor.Descriptor(
  name='MessageNotification',
  full_name='MessageNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MessageNotification.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='MessageNotification.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='MessageNotification.sender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='MessageNotification.subject', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='MessageNotification.body', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=488,
)


_CALLNOTIFICATION = _descriptor.Descriptor(
  name='CallNotification',
  full_name='CallNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='CallNotification.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='CallNotification.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='CallNotification.command', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=555,
)


_MUSICINFO = _descriptor.Descriptor(
  name='MusicInfo',
  full_name='MusicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artist', full_name='MusicInfo.artist', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album', full_name='MusicInfo.album', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track', full_name='MusicInfo.track', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=614,
)

_SETWEATHER.fields_by_name['forecasts'].message_type = _FORECAST
DESCRIPTOR.message_types_by_name['SetTime'] = _SETTIME
DESCRIPTOR.message_types_by_name['MusicControl'] = _MUSICCONTROL
DESCRIPTOR.message_types_by_name['CallControl'] = _CALLCONTROL
DESCRIPTOR.message_types_by_name['Forecast'] = _FORECAST
DESCRIPTOR.message_types_by_name['SetWeather'] = _SETWEATHER
DESCRIPTOR.message_types_by_name['MessageNotification'] = _MESSAGENOTIFICATION
DESCRIPTOR.message_types_by_name['CallNotification'] = _CALLNOTIFICATION
DESCRIPTOR.message_types_by_name['MusicInfo'] = _MUSICINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetTime = _reflection.GeneratedProtocolMessageType('SetTime', (_message.Message,), {
  'DESCRIPTOR' : _SETTIME,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:SetTime)
  })
_sym_db.RegisterMessage(SetTime)

MusicControl = _reflection.GeneratedProtocolMessageType('MusicControl', (_message.Message,), {
  'DESCRIPTOR' : _MUSICCONTROL,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:MusicControl)
  })
_sym_db.RegisterMessage(MusicControl)

CallControl = _reflection.GeneratedProtocolMessageType('CallControl', (_message.Message,), {
  'DESCRIPTOR' : _CALLCONTROL,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:CallControl)
  })
_sym_db.RegisterMessage(CallControl)

Forecast = _reflection.GeneratedProtocolMessageType('Forecast', (_message.Message,), {
  'DESCRIPTOR' : _FORECAST,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:Forecast)
  })
_sym_db.RegisterMessage(Forecast)

SetWeather = _reflection.GeneratedProtocolMessageType('SetWeather', (_message.Message,), {
  'DESCRIPTOR' : _SETWEATHER,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:SetWeather)
  })
_sym_db.RegisterMessage(SetWeather)

MessageNotification = _reflection.GeneratedProtocolMessageType('MessageNotification', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGENOTIFICATION,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:MessageNotification)
  })
_sym_db.RegisterMessage(MessageNotification)

CallNotification = _reflection.GeneratedProtocolMessageType('CallNotification', (_message.Message,), {
  'DESCRIPTOR' : _CALLNOTIFICATION,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:CallNotification)
  })
_sym_db.RegisterMessage(CallNotification)

MusicInfo = _reflection.GeneratedProtocolMessageType('MusicInfo', (_message.Message,), {
  'DESCRIPTOR' : _MUSICINFO,
  '__module__' : 'src.protobuff.smaq2oss_pb2'
  # @@protoc_insertion_point(class_scope:MusicInfo)
  })
_sym_db.RegisterMessage(MusicInfo)


# @@protoc_insertion_point(module_scope)
