/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "smaq2oss.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SetTime, SetTime, AUTO)


PB_BIND(MusicControl, MusicControl, AUTO)


PB_BIND(CallControl, CallControl, AUTO)


PB_BIND(Forecast, Forecast, AUTO)


PB_BIND(SetWeather, SetWeather, AUTO)


PB_BIND(MessageNotification, MessageNotification, AUTO)


PB_BIND(CallNotification, CallNotification, AUTO)


PB_BIND(MusicInfo, MusicInfo, AUTO)



